### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by lfarah** [typelift/Concurrent#30]
Hey @typelift, your library is really interesting.

The only problem I found was the ```README.md```, which is a little bit confusing.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib.

What are your thoughts?

**Comment by CodaFi** [comment]
Hello @lfarah, sorry to get back to you so late.  I'm finishing up the next release of this framework, but I've cut a branch `swift-develop` where we're going to implement support for Swift 3.0 and any README work like this should target that.  Would you mind structuring the README according to your template and shooting us a pull request?  If not I can try my hand at it and ping you when I have a working draft.

Sound good?

**Comment by lfarah** [comment]
I could shoot a pull request. Should I do it right now or when you finish the next release?

**Comment by CodaFi** [comment]
ASAP please.
