### ISSUE TITLE
How do I take a value from MVar or Chan with timeout?

### ISSUE THREAD

**Issue by ethercrow** [typelift/Concurrent#50]
In Haskell, I can use System.Timeout from base. How do I do it in Swift?

**Comment by bkase** [comment]
Hi @ethercrow , unfortunately, there isn't a great solution for this right now.

`pthread_cond_timedwait` could work, but open resources could be left in an inconsistent state when the timeout happens.

Also, if there are two threads and a conditional, the first can spin and wait for the timer to set a condition. As long as you're sure that your work is interruptible, it should work.

We don't have any machinery in this framework to handle timeouts.
